name: CI-QA

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
# on:
#   push:
#     branches: [quality]
on: workflow_dispatch

jobs:
  build:
    # using Ubuntu
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3 # This installs node and npm for us
        with:
          node-version: "18.13"
          cache: npm

      - uses: actions/cache@v3 # this allows for re-using node_modules caching, making builds a bit faster.
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Change Git Protocol and npm Install
        if: steps.cache.outputs.cache-hit != 'true'
        run: git config --global url."git@github.com:".insteadOf git://github.com/ && npm ci

      - name: NPM Install Angular
        run: npm install -g @angular/cli

      - name: NPM build Angular Production
        run: ng build --base-href="./"

      - name: Delete Existing Files
        # run: sudo sshpass -p ${{ secrets.SSH_PROD_PASSKEY }} -v ssh -o StrictHostKeyChecking=no -p 22 ${{ secrets.SSH_PROD_USER }}@${{ secrets.SSH_PROD_HOST }} 'rm -rf /var/www/fsdatabridge/assets/';
        run: sudo sshpass -p ${{ secrets.SSH_PROD_PASSKEY }} -v ssh -o StrictHostKeyChecking=no -p 22 ${{ secrets.SSH_PROD_USER }}@${{ secrets.SSH_PROD_HOST }} 'find /var/www/fsdatabridge/ -type f ! -path "/var/www/fsdatabridge/fsdbbackend/*" -exec rm -f {} + && find /var/www/fsdatabridge/ -type d -empty -delete';

      - name: Compress and Copy New Files to server
        run: |
          cd dist/fs-data-bridge
          tar -czvf ../../fsdatabridge.tar.gz ./
          cd ..
          cd ..
          sudo sshpass -p ${{ secrets.SSH_PASS }} scp -P 3952 -v -o StrictHostKeyChecking=no -r fsdatabridge.tar.gz ${{ secrets.SSH_USER }}@${{ secrets.SSH_PROD_HOST }}:/var/www/fsdatabridge/
      - name: Uncompress new Files
        run: sudo sshpass -p ${{ secrets.SSH_PROD_PASSKEY }} -v ssh -o StrictHostKeyChecking=no -p 22 ${{ secrets.SSH_PROD_USER }}@${{ secrets.SSH_PROD_HOST }} 'cd /var/www/fsdatabridge/ && tar -xzvf fsdatabridge.tar.gz && rm fsdatabridge.tar.gz'
